List contents of target folder

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,21 +36,25 @@ jobs:
           cd target/azure-functions  # Go to azure-functions
           zip -r ../azure-functions-1.0-SNAPSHOT.zip *  # Zip entire azure-functions from within the folder and save it one level up
 
+
+      - name: List contents of target folder
+        run: ls -lart target
+
       - name: Get package filename
         id: get-package
         run: echo "PACKAGE_FILE=target/azure-functions-1.0-SNAPSHOT.zip" >> $GITHUB_ENV  # azure-functions-1.0-SNAPSHOT.zip is our package
 
-      - name: Deploy to Azure Web App
-        uses: azure/webapps-deploy@v2
-        with:
-          app-name: 'coupaapiCall'
-          slot-name: 'production'
-          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
-          package: ${{ env.PACKAGE_FILE }}
+      # - name: Deploy to Azure Web App
+      #   uses: azure/webapps-deploy@v2
+      #   with:
+      #     app-name: 'coupaapiCall'
+      #     slot-name: 'production'
+      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
+      #     package: ${{ env.PACKAGE_FILE }}
 
-      - name: Ensure all processes are stopped
-        run: |
-          pkill -f java || true
+      # - name: Ensure all processes are stopped
+      #   run: |
+      #     pkill -f java || true
 
-      - name: Clean up temporary files
-        run: rm -rf target/deploy
+      # - name: Clean up temporary files
+      #   run: rm -rf target/deploy
